### ISSUE TITLE
[Bug] spacing header to calendar large

### ISSUE THREAD

**Issue by anhvq25** [theideasaler/calendar_date_picker2#5] opened 2022-07-09 16:03 UTC
When i use CalendarDatePicker2() not in ListView. Layout of Calendar is error. Spacing between header and calendar is very large.

**Comment by theideasaler** [comment] 2022-07-10 02:30
hi @anhvq25 can you please provide a minimum reproduceable sample?

**Comment by theideasaler** [comment] 2022-07-10 03:11
@anhvq25 Issue fixed in https://github.com/theideasaler/calendar_date_picker2/commit/97bc1b2af7901e04b0544427fc01be74665e9967. 
Actually this issue is due to (GridView)[https://api.flutter.dev/flutter/widgets/GridView-class.html]'s default behaviour

> _By default, [GridView](https://api.flutter.dev/flutter/widgets/GridView-class.html) will automatically pad the limits of the grids's scrollable to avoid partial obstructions indicated by [MediaQuery](https://api.flutter.dev/flutter/widgets/MediaQuery-class.html)'s padding. To avoid this behavior, override with a zero [padding](https://api.flutter.dev/flutter/widgets/BoxScrollView/padding.html) property._

**Closed by theideasaler** 2022-07-10 03:11 UTC
